[package]
name = "onsa-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
cpal.workspace = true
rtrb.workspace = true
realfft.workspace = true
rubato.workspace = true
symphonia.workspace = true
thiserror.workspace = true
tracing.workspace = true
